site_name: JuliaCookbook
site_description: A cookbook for Julia
repo_url: https://github.com/pranavtbhat/JuliaCookbook

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- [index.md, Contents]
- [arrays/arrays.md            , Arrays    , Introduction]
- [arrays/creating.md          , Arrays    , Creation]
- [arrays/map.md               , Arrays    , Iteration]
- [arrays/append.md            , Arrays    , Concatenation]
- [arrays/reorder.md           , Arrays    , Reordering]
- [arrays/setlike.md           , Arrays    , Set Operations]
- [arrays/search.md            , Arrays    , Searching]
- [tuples.md                   , Tuples]
- [strings.md                  , Strings]
- [dicts.md                    , Dictionaries]
- [dates.md                    , Dates]
- [regex.md                    , Regular Expressions]
- [dataframes/DataFrames.md    , DataFrames, Introduction]
- [dataframes/file_input.md    , DataFrames, File IO]
- [dataframes/accessors.md     , DataFrames, Data Access]
- [dataframes/RDatasets.md     , DataFrames, R Datasets]
- [dataframes/regressions      , DataFrames, Regressions]
