site_name: JuliaCookbook
site_description: A cookbook for Julia
repo_url: https://github.com/pranavtbhat/JuliaCookbook

theme: cinder

extra_css:
  - assets/Documenter.css

markdown_extensions:
- extra
 - mdx_math
 - fenced_code
 - toc:
     permalink: True

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Tuples: tuples.md
- Strings: strings.md
- Dictionaries: dicts.md
- Dates: dates.md
- Regex: regex.md
- Arrays: arrays.md
- Dates: dates.md
- DataFrames: dataframes.md
